/*
 * adc_dma.c — paddle + audio ADC → DMA2 → FSMC/FPGA streams (STM32F407).
 *
 * See adc_dma.h and docs/stm32f407_paddle_adc_dma_fsmc.md.
 *
 * The peripheral handles (hadc2/hadc1) and the DMA handles are generated by
 * CubeMX in Core/Src/main.c and stm32f4xx_hal_msp.c. This module drives the
 * start/stop sequencing and the paddle GPIO clamp. It does NOT re-init the
 * peripherals — it assumes MX_ADC1_Init / MX_ADC2_Init / MX_DMA_Init and the
 * MSP __HAL_LINKDMA have already run.
 *
 * IMPORTANT — the DMA writes go to FSMC (device memory), not SRAM. HAL_ADC_Start_DMA
 * takes a uint32_t* destination and does word-sized bookkeeping, but the actual
 * bus transfers are 16-bit because we set both PeriphDataAlignment and
 * MemDataAlignment to HALFWORD in CubeMX. We pass the FPGA halfword address cast
 * to uint32_t*; length is the number of conversions (8 / 4), NOT bytes.
 */
#include "adc_dma.h"

#if defined(FPGA_BUS_STM32)

/* Handles owned by CubeMX (Core/Src/main.c). */
extern ADC_HandleTypeDef hadc2;   /* paddle: 8-rank continuous scan          */
extern ADC_HandleTypeDef hadc1;   /* audio:  4-rank timer-triggered scan     */
extern TIM_HandleTypeDef htim2;   /* audio ADC trigger (TRGO on update)       */

volatile adc_dma_fault_info_t adc_dma_last_fault;

/* HAL_ADC_Start_DMA() deliberately uses HAL_DMA_Start_IT(), even when the
 * application has no use for buffer-completion callbacks.  For the paddle
 * stream that would produce one half-transfer IRQ every four conversions and
 * one transfer-complete IRQ every eight conversions.  A free-running ADC can
 * consequently spend essentially all CPU time in DMA2_Stream2_IRQHandler and
 * starve ThreadX.
 *
 * Keep the DMA error sources enabled, but turn off the two normal completion
 * sources immediately after HAL has armed the stream.  Circular DMA continues
 * in hardware; these bits control only interrupt generation. */
static void adc_dma_disable_completion_irqs(ADC_HandleTypeDef *hadc)
{
    __HAL_DMA_DISABLE_IT(hadc->DMA_Handle, DMA_IT_HT | DMA_IT_TC);
}

/* ------------------------------------------------------------------ */
/* Stream start / stop                                                 */
/* ------------------------------------------------------------------ */
/*
 * HAL_ADC_Start_DMA(hadc, pData, Length):
 *   pData  = DMA memory (destination) address. We hand it the FPGA register
 *            address; MINC walks it through the 8 (or 4) consecutive halfword
 *            regs, then circular mode wraps it back to the base.
 *   Length = number of ADC conversions per DMA "buffer" = NDTR. With CIRC=1
 *            the controller reloads NDTR automatically, so this is the wrap
 *            length, exactly the 8 / 4 from the interface contract.
 *
 * Circular + DMAContinuousRequests(DDS)=1 (set in CubeMX) means the stream
 * runs forever with no CPU involvement after this call.
 */

fpga_status_t adc_dma_paddle_start(void)
{
    /* Clear any stale error state before arming (design doc: clear old DMA
     * status flags before enabling the stream). HAL does the flag clears
     * inside Start_DMA, but we also make sure the ADC isn't left in an
     * overrun-latched state from a previous run. */
    __HAL_ADC_CLEAR_FLAG(&hadc2, ADC_FLAG_OVR);

    if (HAL_ADC_Start_DMA(&hadc2,
                          (uint32_t *)FPGA_PADDLE_ADC_ADDR,
                          FPGA_PADDLE_ADC_COUNT) != HAL_OK) {
        return FPGA_ERR_STATE;
    }
    adc_dma_disable_completion_irqs(&hadc2);
    return FPGA_OK;
}

fpga_status_t adc_dma_audio_start(void)
{
    __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_OVR);

    /* CONT=0: the ADC waits for each TIM2 trigger to run one 4-rank scan.
     * DDS=1 keeps DMA requests alive across triggers.  MX_TIM2_Init only
     * configures the timer; it does not set TIM_CR1.CEN, so start the trigger
     * after the ADC/DMA have been armed.  Previously no code started TIM2 and
     * consequently ADC1 produced no conversions or FSMC writes. */
    if (HAL_ADC_Start_DMA(&hadc1,
                          (uint32_t *)FPGA_AUDIO_ADC_ADDR,
                          FPGA_AUDIO_ADC_COUNT) != HAL_OK) {
        return FPGA_ERR_STATE;
    }
    adc_dma_disable_completion_irqs(&hadc1);

    if (HAL_TIM_Base_Start(&htim2) != HAL_OK) {
        (void)HAL_ADC_Stop_DMA(&hadc1);
        return FPGA_ERR_STATE;
    }
    return FPGA_OK;
}

void adc_dma_paddle_stop(void) { (void)HAL_ADC_Stop_DMA(&hadc2); }
void adc_dma_audio_stop(void)
{
    /* Stop new triggers before disarming their consumer. */
    (void)HAL_TIM_Base_Stop(&htim2);
    (void)HAL_ADC_Stop_DMA(&hadc1);
}

/* ------------------------------------------------------------------ */
/* POTGO / POT_RESET paddle-pin clamp                                  */
/* ------------------------------------------------------------------ */
/*
 * On this board (0.51 errata applied) the eight paddle ADC inputs are:
 *   ranks 0..3 : PC0 PC1 PC2 PC3
 *   ranks 4..7 : PA0 PA1 PA4 PA5
 * i.e. split across GPIOC and GPIOA. The design doc's "one precomputed MODER
 * write" is therefore not possible; we compute a masked MODER update per port.
 *
 * We switch between ANALOG mode (0b11) and push-pull OUTPUT mode (0b01) by
 * editing only the 2-bit MODER fields for our pins, leaving every other pin on
 * the port untouched. BSRR preloads the output latch low first so enabling the
 * output driver never drives a transient high.
 *
 * These run in ISR context and must be fast and allocation-free — raw register
 * writes only, no HAL_GPIO_Init (which is slow and takes a critical section).
 */

/* Build the AND-mask that clears the MODER fields for the given pin mask, and
 * the OR-value that sets those fields to `mode` (0b01 output, 0b11 analog). */
static inline void moder_update(GPIO_TypeDef *port, uint32_t pin_mask, uint32_t mode2)
{
    uint32_t clear = 0, set = 0;
    for (uint32_t p = 0; p < 16; ++p) {
        if (pin_mask & (1u << p)) {
            clear |= (0x3u << (p * 2));
            set   |= (mode2 << (p * 2));
        }
    }
    /* Single RMW per port. ISR context: brief, and the paddle MODER fields are
     * not touched anywhere else, so no lock is needed against other threads. */
    port->MODER = (port->MODER & ~clear) | set;
}

#define MODE_OUTPUT_2  0x1u   /* MODER field = 01: general-purpose output   */
#define MODE_ANALOG_2  0x3u   /* MODER field = 11: analog                   */

void adc_dma_paddle_pins_clamp(void)
{
    /* 1. Preload output latches low FIRST (BSRR reset half = high 16 bits). */
    FPGA_PADDLE_PC_PORT->BSRR = (uint32_t)FPGA_PADDLE_PC_PINS << 16;
    FPGA_PADDLE_PA_PORT->BSRR = (uint32_t)FPGA_PADDLE_PA_PINS << 16;
    /* 2. analog -> push-pull output-low. */
    moder_update(FPGA_PADDLE_PC_PORT, FPGA_PADDLE_PC_PINS, MODE_OUTPUT_2);
    moder_update(FPGA_PADDLE_PA_PORT, FPGA_PADDLE_PA_PINS, MODE_OUTPUT_2);
}

void adc_dma_paddle_pins_release(void)
{
    /* output -> analog. ADC/DMA are still running; sampling resumes now. */
    moder_update(FPGA_PADDLE_PC_PORT, FPGA_PADDLE_PC_PINS, MODE_ANALOG_2);
    moder_update(FPGA_PADDLE_PA_PORT, FPGA_PADDLE_PA_PINS, MODE_ANALOG_2);
}

/* ------------------------------------------------------------------ */
/* Fault hook                                                          */
/* ------------------------------------------------------------------ */
/* Weak so production code can override this with its desired recovery policy.
 * The default deliberately returns: trapping here makes an ADC/DMA fault look
 * exactly like a scheduler hang.  adc_dma_last_fault retains the evidence for
 * a debugger, including the DMA raw status registers. */
__attribute__((weak))
void adc_dma_on_fault(ADC_HandleTypeDef *hadc, uint32_t err)
{
    (void)hadc; (void)err;
}

/* HAL calls this on ADC error (including OVR) if the ADC IRQ is enabled.
 * We route both ADCs through the single fault hook. */
void HAL_ADC_ErrorCallback(ADC_HandleTypeDef *hadc)
{
    const uint32_t err = HAL_ADC_GetError(hadc);

    /* Write count last so a debugger never mistakes a partially updated
     * snapshot for a new record.  Do not clear any peripheral flags here;
     * HAL owns that sequencing and the raw DMA flags are valuable evidence. */
    adc_dma_last_fault.adc_instance = (uint32_t)hadc->Instance;
    adc_dma_last_fault.error = err;
    adc_dma_last_fault.adc_sr = hadc->Instance->SR;
    adc_dma_last_fault.adc_cr1 = hadc->Instance->CR1;
    adc_dma_last_fault.adc_cr2 = hadc->Instance->CR2;
    adc_dma_last_fault.dma_cr = hadc->DMA_Handle->Instance->CR;
    adc_dma_last_fault.dma_ndtr = hadc->DMA_Handle->Instance->NDTR;
    adc_dma_last_fault.dma_fcr = hadc->DMA_Handle->Instance->FCR;
    adc_dma_last_fault.dma_lisr = DMA2->LISR;
    adc_dma_last_fault.dma_hisr = DMA2->HISR;
    __DMB();
    adc_dma_last_fault.count++;

    adc_dma_on_fault(hadc, err);
}

#endif /* FPGA_BUS_STM32 */
